[pytest]
asyncio_mode = auto
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
norecursedirs = app/database app/models app/schemas app/service app/repository app/routers app/core app/dependencies